version: "3"

services:

  app:
    build: .
    volumes:
      - ./:/var/www/html/
    ports:
      - 9901:80
    networks:
      - hk-demin
    environment:
      - QUEUE_DEV=true

  db:
    image: postgres:alpine
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - hk-demin

  redis:
    image: redis:4.0.14
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env
    networks:
      - hk-demin

networks:
  hk-demin:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28
