version: "3"

services:

  app:
    build: .
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:8080"
    networks:
      - hk-demin
    environment:
      - QUEUE_DEV=true

  db:
    image: postgres:alpine
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    user: "${DOCKER_UID}:${DOCKER_GID}"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - hk-demin

  redis:
    image: redis:4.0.14
    user: "${DOCKER_UID}:${DOCKER_GID}"
    ports:
      - ${REDIS_PORT}:6379
    env_file:
      - .env
    networks:
      - hk-demin

networks:
  hk-demin:
    driver: bridge
